export const jurisdictions = [
  { id: 'bangladesh', name: 'Bangladesh', shortName: 'BD', citationStyle: 'Bangladesh practice note' },
  { id: 'england-wales', name: 'England & Wales', shortName: 'E&W', citationStyle: 'OSCOLA-style' },
  { id: 'united-states', name: 'United States', shortName: 'US', citationStyle: 'Bluebook-style' },
];

export const practiceAreas = [
  'Criminal',
  'Road Accident / Personal Injury',
  'Land / Property',
  'Contract / Commercial',
  'Constitutional / Human Rights',
];

export const cases = [
  {
    id: 'bd-001',
    title: 'Bangladesh Legal Aid and Services Trust v Bangladesh',
    jurisdiction: 'bangladesh',
    practiceArea: 'Criminal',
    court: 'High Court Division',
    year: '2003',
    citation: '55 DLR (HCD) 363',
    location: 'Dhaka, Bangladesh',
    sourceLabel: 'BLAST / section 54 guidelines materials',
    sourceUrl: 'https://www.blast.org.bd/issues/criminal-justice/500-section-54',
    facts: 'A public interest challenge questioned arrest without warrant and remand practices under sections 54 and 167 of the Code of Criminal Procedure.',
    issue: 'Whether arrest and remand powers were being used inconsistently with constitutional guarantees of liberty and protection of law.',
    decision: 'The court issued safeguards and directions for arrest, detention, medical examination, and remand oversight.',
    principle: 'Police powers must be exercised with constitutional accountability, recorded reasons, and judicial scrutiny.',
    statutes: ['Constitution arts 31, 32, 35', 'Code of Criminal Procedure ss 54, 167'],
    lawyerNote: 'Use for bail, unlawful detention, remand opposition, habeas-style urgent filings, and police accountability arguments.',
    keywords: ['arrest', 'remand', 'police power', 'liberty', 'criminal procedure'],
  },
  {
    id: 'bd-002',
    title: 'State v Md Sukur Ali',
    jurisdiction: 'bangladesh',
    practiceArea: 'Criminal',
    court: 'Appellate Division',
    year: '2004',
    citation: '9 BLC (AD) 238',
    location: 'Bangladesh',
    sourceLabel: 'Cornell Death Penalty Worldwide summary',
    sourceUrl: 'https://deathpenaltyworldwide.org/database/#/results/country?id=7',
    facts: 'A young accused faced a mandatory death sentence framework in a serious criminal case.',
    issue: 'Whether mandatory death sentencing can stand without individualized judicial sentencing discretion.',
    decision: 'The case is commonly cited in Bangladesh discussions on mandatory death penalty and individualized sentencing.',
    principle: 'Capital sentencing demands careful judicial scrutiny of culpability, mitigation, and proportionality.',
    statutes: ['Penal Code ss 302, 376', 'Constitution arts 31, 35'],
    lawyerNote: 'Use as a mitigation and proportionality authority when arguing against mechanical capital sentencing.',
    keywords: ['death penalty', 'sentencing', 'mitigation', 'juvenile', 'criminal'],
  },
  {
    id: 'bd-003',
    title: 'Anwar Hossain Chowdhury v Bangladesh',
    jurisdiction: 'bangladesh',
    practiceArea: 'Constitutional / Human Rights',
    court: 'Appellate Division',
    year: '1989',
    citation: '41 DLR (AD) 165',
    location: 'Dhaka, Bangladesh',
    sourceLabel: 'ConstitutionNet case summary',
    sourceUrl: 'https://constitutionnet.org/vl/item/anwar-hossain-chowdhury-v-bangladesh',
    facts: 'The Eighth Amendment altered constitutional arrangements, including permanent benches outside Dhaka.',
    issue: 'Whether Parliament can amend the Constitution in a way that damages its basic structure.',
    decision: 'The Appellate Division recognized limits on constitutional amendment power.',
    principle: 'The basic structure doctrine limits constitutional amendments that destroy core constitutional identity.',
    statutes: ['Constitution art 142', 'Constitution arts 7, 26, 94'],
    lawyerNote: 'Use for constitutional amendment challenges, judicial independence, and rule-of-law submissions.',
    keywords: ['basic structure', 'constitutional amendment', 'judicial independence'],
  },
  {
    id: 'bd-004',
    title: 'Secretary, Ministry of Finance v Masdar Hossain',
    jurisdiction: 'bangladesh',
    practiceArea: 'Constitutional / Human Rights',
    court: 'Appellate Division',
    year: '1999',
    citation: '52 DLR (AD) 82',
    location: 'Bangladesh',
    sourceLabel: 'International Commission of Jurists profile',
    sourceUrl: 'https://www.icj.org/bangladesh-judiciary-separation-from-the-executive-an-essential-step-for-rule-of-law/',
    facts: 'Judicial officers challenged executive control over the subordinate judiciary.',
    issue: 'Whether constitutional separation of powers required institutional separation of the judiciary from the executive.',
    decision: 'The court issued directions for separation and judicial service arrangements.',
    principle: 'Independent courts require institutional separation, secure service conditions, and executive non-interference.',
    statutes: ['Constitution arts 22, 109, 115, 116'],
    lawyerNote: 'Strong authority for independence of judiciary, tribunal design, and rule of law submissions.',
    keywords: ['judiciary', 'separation of powers', 'rule of law'],
  },
  {
    id: 'bd-005',
    title: 'Bangladesh Italian Marble Works Ltd v Government of Bangladesh',
    jurisdiction: 'bangladesh',
    practiceArea: 'Constitutional / Human Rights',
    court: 'Appellate Division',
    year: '2010',
    citation: '62 DLR (AD) 298',
    location: 'Dhaka, Bangladesh',
    sourceLabel: 'Supreme Court of Bangladesh judgment',
    sourceUrl: 'https://www.supremecourt.gov.bd/resources/documents/421033_C.A.No.1044of2009.pdf',
    facts: 'The Fifth Amendment and martial-law-era constitutional changes were challenged.',
    issue: 'Whether martial law proclamations and constitutional validation of extra-constitutional rule were valid.',
    decision: 'The Appellate Division rejected constitutional validation of martial law arrangements.',
    principle: 'Supremacy of the Constitution and rule of law cannot be displaced by martial law legitimacy.',
    statutes: ['Constitution arts 7, 26, 142'],
    lawyerNote: 'Use for constitutional supremacy, legality, and limits of validating past executive action.',
    keywords: ['martial law', 'constitutional supremacy', 'fifth amendment'],
  },
  {
    id: 'bd-006',
    title: 'Kazi Mukhlesur Rahman v Bangladesh',
    jurisdiction: 'bangladesh',
    practiceArea: 'Constitutional / Human Rights',
    court: 'Appellate Division',
    year: '1974',
    citation: '26 DLR (SC) 44',
    location: 'Bangladesh',
    sourceLabel: 'Bangladesh PIL Repository',
    sourceUrl: 'https://bdpil.org/',
    facts: 'A constitutional challenge raised public interest issues beyond a narrow personal-rights model.',
    issue: 'Whether a public-spirited applicant could maintain a constitutional petition in matters of national importance.',
    decision: 'The court treated standing flexibly in appropriate constitutional matters.',
    principle: 'Public interest standing is available where a serious constitutional or public duty issue is raised.',
    statutes: ['Constitution art 102'],
    lawyerNote: 'Use when defending maintainability of public interest writ petitions.',
    keywords: ['locus standi', 'public interest litigation', 'article 102'],
  },
  {
    id: 'bd-007',
    title: 'Dr Mohiuddin Farooque v Bangladesh',
    jurisdiction: 'bangladesh',
    practiceArea: 'Land / Property',
    court: 'Appellate Division',
    year: '1997',
    citation: '49 DLR (AD) 1',
    location: 'Bangladesh',
    sourceLabel: 'BELA case materials',
    sourceUrl: 'https://belabangla.org/category/judgements/',
    facts: 'Environmental public interest litigation expanded access to court for community and environmental harm.',
    issue: 'Whether environmental degradation and public injury can support representative constitutional litigation.',
    decision: 'The court recognized broader standing in public interest environmental litigation.',
    principle: 'Environmental protection, life, and public rights may be litigated by public interest petitioners.',
    statutes: ['Constitution arts 31, 32, 102', 'Environment Conservation Act 1995'],
    lawyerNote: 'Use for land-use, environmental clearance, waterbody, and public-rights litigation.',
    keywords: ['environment', 'standing', 'public interest', 'land use'],
  },
  {
    id: 'bd-008',
    title: 'BELA v Bangladesh / Modhumoti Model Town',
    jurisdiction: 'bangladesh',
    practiceArea: 'Land / Property',
    court: 'Appellate Division',
    year: '2012',
    citation: '65 DLR (AD) 181',
    location: 'Amin Bazar, Savar, Bangladesh',
    sourceLabel: 'Supreme Court of Bangladesh judgment',
    sourceUrl: 'https://www.supremecourt.gov.bd/resources/documents/450586_C.A.256of2009.pdf',
    facts: 'A housing project was challenged for filling flood-flow zones and wetlands contrary to planning and environmental controls.',
    issue: 'Whether private housing development could proceed despite flood-flow, wetland, and planning law restrictions.',
    decision: 'The courts treated unlawful conversion of protected land as contrary to public interest and environmental law.',
    principle: 'Development rights are constrained by flood-flow protection, environmental law, and planned urban governance.',
    statutes: ['Environment Conservation Act 1995', 'Natural Water Reservoir Conservation Act 2000', 'Town Improvement Act 1953'],
    lawyerNote: 'Use in land development, wetland filling, RAJUK clearance, and public environmental injury cases.',
    keywords: ['wetland', 'housing', 'land development', 'flood-flow zone'],
  },
  {
    id: 'bd-009',
    title: 'WP No 14633 of 2018: Ambulance death during transport strike',
    jurisdiction: 'bangladesh',
    practiceArea: 'Road Accident / Personal Injury',
    court: 'High Court Division',
    year: '2018',
    citation: 'Writ Petition No 14633 of 2018',
    location: 'Moulvibazar, Bangladesh',
    sourceLabel: 'Bangladesh PIL Repository',
    sourceUrl: 'https://bdpil.org/2020/11/18/331/',
    facts: 'A seven-day-old baby died in an ambulance after alleged obstruction during a transport strike.',
    issue: 'Whether state authorities and transport bodies failed to protect life, emergency movement, and access to justice.',
    decision: 'The petition sought constitutional relief, accountability, and compensation-oriented directions.',
    principle: 'Road obstruction and transport disruption can raise constitutional right-to-life and emergency-access issues.',
    statutes: ['Constitution arts 31, 32, 102', 'Road Transport Act 2018'],
    lawyerNote: 'Use for emergency access, transport strike liability, and compensation claims after road-related death.',
    keywords: ['road accident', 'transport strike', 'ambulance', 'compensation'],
  },
  {
    id: 'bd-010',
    title: 'Suo Moto Rule No 05 of 2018: Bus accident and driver licensing',
    jurisdiction: 'bangladesh',
    practiceArea: 'Road Accident / Personal Injury',
    court: 'High Court Division',
    year: '2018',
    citation: 'Suo Moto Rule No 05 of 2018',
    location: 'Dhaka, Bangladesh',
    sourceLabel: 'Bangladesh PIL Repository',
    sourceUrl: 'https://bdpil.org/2018/08/04/335/',
    facts: 'The High Court responded to reports of serious bus accidents caused by rash and negligent driving.',
    issue: 'Whether licensing and regulatory authorities should act against drivers and transport operators after fatal accidents.',
    decision: 'The court issued a suo motu rule and interim licensing directions against drivers involved in the incident.',
    principle: 'Regulators may be compelled to act promptly where road safety failures threaten life and public safety.',
    statutes: ['Constitution arts 31, 32', 'Road Transport Act 2018'],
    lawyerNote: 'Use for urgent regulatory directions, BRTA action, and public safety writs.',
    keywords: ['bus accident', 'rash driving', 'BRTA', 'licence'],
  },
  {
    id: 'bd-011',
    title: 'Catherine Masud compensation claim after Tareque Masud road death',
    jurisdiction: 'bangladesh',
    practiceArea: 'Road Accident / Personal Injury',
    court: 'High Court Division',
    year: '2017',
    citation: 'Road accident compensation claim, High Court Division',
    location: 'Manikganj, Bangladesh',
    sourceLabel: 'BLAST press release',
    sourceUrl: 'https://blast.org.bd/2024/08/13/6975/',
    facts: 'Filmmaker Tareque Masud, Mishuk Munier, and others died in a 2011 road crash; family members pursued compensation.',
    issue: 'How civil compensation and accountability should operate after fatal negligent driving.',
    decision: 'The High Court awarded compensation; appellate proceedings were reported as pending by BLAST.',
    principle: 'Fatal road accident claims require proof of negligence, loss, dependency, and enforceable compensation remedies.',
    statutes: ['Fatal Accidents Act 1855', 'Penal Code s 304A', 'Road Transport Act 2018 ss 53, 54, 105'],
    lawyerNote: 'Use as a demo anchor for damages calculation, dependency evidence, and transport-liability strategy.',
    keywords: ['road death', 'compensation', 'fatal accident', 'negligence'],
  },
  {
    id: 'bd-012',
    title: 'WP No 4102 of 2016: Ria Moni construction-site death',
    jurisdiction: 'bangladesh',
    practiceArea: 'Road Accident / Personal Injury',
    court: 'High Court Division',
    year: '2016',
    citation: 'Writ Petition No 4102 of 2016',
    location: 'Rampura, Dhaka, Bangladesh',
    sourceLabel: 'Bangladesh PIL Repository',
    sourceUrl: 'https://bdpil.org/2016/04/03/129/',
    facts: 'A four-year-old girl died after an iron rod fell from a building under construction near a public road.',
    issue: 'Whether public authorities and builders failed to enforce construction-safety duties under building rules.',
    decision: 'The court issued a rule on safety failures and fundamental-rights violations.',
    principle: 'Unsafe construction adjoining public spaces can trigger constitutional and tort-style public safety remedies.',
    statutes: ['Constitution arts 27, 31, 32', 'Bangladesh National Building Code'],
    lawyerNote: 'Use for public nuisance, construction negligence, compensation, and regulatory enforcement prayers.',
    keywords: ['construction accident', 'public safety', 'negligence', 'compensation'],
  },
  {
    id: 'bd-013',
    title: 'WP No 2019 of 2006: KTS Garments fire',
    jurisdiction: 'bangladesh',
    practiceArea: 'Road Accident / Personal Injury',
    court: 'High Court Division',
    year: '2006',
    citation: 'Writ Petition No 2019 of 2006',
    location: 'Chittagong, Bangladesh',
    sourceLabel: 'Bangladesh PIL Repository',
    sourceUrl: 'https://bdpil.org/2006/03/06/280/',
    facts: 'A factory fire killed 57 workers amid allegations of locked exits and inadequate emergency safety.',
    issue: 'Whether authorities failed to investigate, prosecute, and prevent industrial deaths and injuries.',
    decision: 'The court issued rule nisi and required investigation reporting.',
    principle: 'Industrial safety failures can engage life, labour, criminal investigation, and compensation obligations.',
    statutes: ['Fatal Accidents Act 1855', 'Bangladesh Labour Act 2006', 'Constitution arts 31, 32'],
    lawyerNote: 'Use for workplace injury, fatal accident compensation, and safety enforcement.',
    keywords: ['factory fire', 'workers', 'fatal accident', 'safety'],
  },
  {
    id: 'bd-014',
    title: 'WP No 2718 of 2024: Baily Road fire safety',
    jurisdiction: 'bangladesh',
    practiceArea: 'Road Accident / Personal Injury',
    court: 'High Court Division',
    year: '2024',
    citation: 'Writ Petition No 2718 of 2024',
    location: 'Baily Road, Dhaka, Bangladesh',
    sourceLabel: 'Bangladesh PIL Repository',
    sourceUrl: 'https://bdpil.org/2024/03/10/wp-2718-of-2024/',
    facts: 'After deaths and injuries in a commercial building fire, petitioners sought safety compliance and compensation.',
    issue: 'Whether state and city authorities failed to enforce fire safety, zoning, and building-safety duties.',
    decision: 'The petition sought directions for compensation, fire-safety rooms, stairs, and strict compliance.',
    principle: 'Public authorities may face constitutional scrutiny for preventable fire-safety failures.',
    statutes: ['Fire Prevention and Extinguishing Act 2003', 'Bangladesh National Building Code 2020', 'Constitution arts 31, 32'],
    lawyerNote: 'Use for recent public safety litigation, casualty compensation, and emergency compliance prayers.',
    keywords: ['fire safety', 'compensation', 'building code', 'public safety'],
  },
  {
    id: 'bd-015',
    title: 'WP No 8119 of 2024: Slum eviction and rehabilitation',
    jurisdiction: 'bangladesh',
    practiceArea: 'Land / Property',
    court: 'High Court Division',
    year: '2024',
    citation: 'Writ Petition No 8119 of 2024',
    location: 'Dhaka, Bangladesh',
    sourceLabel: 'Bangladesh PIL Repository',
    sourceUrl: 'https://bdpil.org/2024/07/11/wp-8119-of-2024/',
    facts: 'Petitioners challenged eviction steps against slum dwellers without alternative rehabilitation arrangements.',
    issue: 'Whether eviction without rehabilitation violated rights to life, protection of law, safety, and shelter.',
    decision: 'The High Court issued rule nisi requiring authorities to justify the eviction process.',
    principle: 'State land management and eviction must consider due process, rehabilitation, and constitutional protection.',
    statutes: ['Constitution arts 27, 31, 32, 42, 102'],
    lawyerNote: 'Use for eviction injunctions, rehabilitation demands, and rights-based property arguments.',
    keywords: ['eviction', 'rehabilitation', 'shelter', 'property'],
  },
  {
    id: 'bd-016',
    title: 'BGMEA Building case',
    jurisdiction: 'bangladesh',
    practiceArea: 'Land / Property',
    court: 'Appellate Division',
    year: '2016',
    citation: 'Civil Petition for Leave to Appeal No 1162 of 2013',
    location: 'Hatirjheel, Dhaka, Bangladesh',
    sourceLabel: 'Supreme Court of Bangladesh judgment',
    sourceUrl: 'https://www.supremecourt.gov.bd/resources/documents/968131_CP_No_1162_of_2013.pdf',
    facts: 'A prominent building was challenged as unauthorized and inconsistent with public land-use and environmental controls.',
    issue: 'Whether an unauthorized structure could remain where land use and environmental regulations were violated.',
    decision: 'The Appellate Division refused to protect the unauthorized construction.',
    principle: 'Powerful private or institutional actors cannot regularize unlawful construction over public planning controls.',
    statutes: ['Environment Conservation Act 1995', 'Town Improvement Act 1953', 'Building Construction Act 1952'],
    lawyerNote: 'Use for demolition, unauthorized construction, public land, and environmental compliance matters.',
    keywords: ['unauthorized building', 'public land', 'environment', 'planning'],
  },
  {
    id: 'uk-001',
    title: 'Donoghue v Stevenson',
    jurisdiction: 'england-wales',
    practiceArea: 'Road Accident / Personal Injury',
    court: 'House of Lords',
    year: '1932',
    citation: '[1932] AC 562',
    location: 'Paisley, Scotland; common law authority used across UK tort law',
    sourceLabel: 'BAILII',
    sourceUrl: 'https://www.bailii.org/uk/cases/UKHL/1932/100.html',
    facts: 'A consumer alleged illness after drinking ginger beer containing a decomposed snail.',
    issue: 'Whether a manufacturer owed a duty of care to an ultimate consumer absent direct contract.',
    decision: 'The House of Lords recognized a duty of care in negligence.',
    principle: 'The neighbour principle anchors modern negligence duty analysis.',
    statutes: ['Common law negligence'],
    lawyerNote: 'Use as the starting authority for duty of care before moving to modern Caparo-style analysis.',
    keywords: ['negligence', 'duty of care', 'personal injury', 'consumer'],
  },
  {
    id: 'uk-002',
    title: 'Nettleship v Weston',
    jurisdiction: 'england-wales',
    practiceArea: 'Road Accident / Personal Injury',
    court: 'Court of Appeal',
    year: '1971',
    citation: '[1971] 2 QB 691',
    location: 'England & Wales',
    sourceLabel: 'BAILII',
    sourceUrl: 'https://www.bailii.org/ew/cases/EWCA/Civ/1971/6.html',
    facts: 'A learner driver injured an instructor while driving under supervision.',
    issue: 'Whether a learner driver is held to a lower standard of care.',
    decision: 'The learner driver was held to the standard of a reasonably competent driver.',
    principle: 'Road users are judged by an objective standard, not personal inexperience.',
    statutes: ['Road Traffic Act 1988', 'Common law negligence'],
    lawyerNote: 'Use in road accident pleadings where the defendant claims inexperience or lack of skill.',
    keywords: ['learner driver', 'road accident', 'standard of care'],
  },
  {
    id: 'uk-003',
    title: 'Montgomery v Lanarkshire Health Board',
    jurisdiction: 'england-wales',
    practiceArea: 'Road Accident / Personal Injury',
    court: 'UK Supreme Court',
    year: '2015',
    citation: '[2015] UKSC 11',
    location: 'United Kingdom',
    sourceLabel: 'UK Supreme Court',
    sourceUrl: 'https://www.supremecourt.uk/cases/uksc-2013-0136.html',
    facts: 'A patient was not warned of a material childbirth risk relevant to her decision-making.',
    issue: 'What duty a doctor owes when advising on material medical risks and alternatives.',
    decision: 'The Supreme Court emphasized patient autonomy and material-risk disclosure.',
    principle: 'Professional advice must disclose material risks a reasonable person in the patient position would likely consider significant.',
    statutes: ['Common law negligence', 'Human Rights Act 1998 context'],
    lawyerNote: 'Use for informed consent, professional negligence, and risk-disclosure pleadings.',
    keywords: ['medical negligence', 'informed consent', 'personal injury'],
  },
  {
    id: 'uk-004',
    title: 'Robinson v Chief Constable of West Yorkshire Police',
    jurisdiction: 'england-wales',
    practiceArea: 'Road Accident / Personal Injury',
    court: 'UK Supreme Court',
    year: '2018',
    citation: '[2018] UKSC 4',
    location: 'England & Wales',
    sourceLabel: 'UK Supreme Court',
    sourceUrl: 'https://www.supremecourt.uk/cases/uksc-2016-0082.html',
    facts: 'An elderly pedestrian was injured during a police attempt to arrest a suspect in public.',
    issue: 'Whether police owed a duty of care in operational arrest circumstances causing injury to a passer-by.',
    decision: 'The Supreme Court found ordinary negligence principles could apply.',
    principle: 'Public authorities are not immune from ordinary negligence where their positive conduct causes foreseeable injury.',
    statutes: ['Common law negligence'],
    lawyerNote: 'Use for public-authority negligence and injury caused by operational conduct.',
    keywords: ['police', 'duty of care', 'public authority', 'injury'],
  },
  {
    id: 'uk-005',
    title: 'R v Jogee',
    jurisdiction: 'england-wales',
    practiceArea: 'Criminal',
    court: 'UK Supreme Court',
    year: '2016',
    citation: '[2016] UKSC 8',
    location: 'England & Wales',
    sourceLabel: 'UK Supreme Court',
    sourceUrl: 'https://www.supremecourt.uk/cases/uksc-2015-0015.html',
    facts: 'The appeal reconsidered joint enterprise liability for secondary parties.',
    issue: 'Whether foresight of a principal offence was enough for accessory liability.',
    decision: 'The court corrected the law: foresight is evidence of intent, not a substitute for intent.',
    principle: 'Secondary liability requires proof of intentional assistance or encouragement with the required mental element.',
    statutes: ['Accessories and Abettors Act 1861', 'Common law complicity'],
    lawyerNote: 'Use in murder, robbery, group violence, and appeal reviews involving joint enterprise.',
    keywords: ['joint enterprise', 'secondary liability', 'mens rea'],
  },
  {
    id: 'uk-006',
    title: 'Woolmington v Director of Public Prosecutions',
    jurisdiction: 'england-wales',
    practiceArea: 'Criminal',
    court: 'House of Lords',
    year: '1935',
    citation: '[1935] AC 462',
    location: 'England & Wales',
    sourceLabel: 'BAILII',
    sourceUrl: 'https://www.bailii.org/uk/cases/UKHL/1935/1.html',
    facts: 'A murder conviction raised the question of who bore the burden on intent and accident.',
    issue: 'Whether the accused must prove innocence or the prosecution must prove guilt.',
    decision: 'The House of Lords affirmed the prosecution burden beyond reasonable doubt.',
    principle: 'The golden thread of criminal law is that the prosecution must prove guilt.',
    statutes: ['Common law criminal evidence'],
    lawyerNote: 'Use in submissions on burden, standard of proof, and jury directions.',
    keywords: ['burden of proof', 'criminal evidence', 'reasonable doubt'],
  },
  {
    id: 'uk-007',
    title: 'R v Brown',
    jurisdiction: 'england-wales',
    practiceArea: 'Criminal',
    court: 'House of Lords',
    year: '1993',
    citation: '[1993] UKHL 19',
    location: 'England & Wales',
    sourceLabel: 'BAILII',
    sourceUrl: 'https://www.bailii.org/uk/cases/UKHL/1993/19.html',
    facts: 'Consensual sadomasochistic activities caused actual bodily harm and worse.',
    issue: 'Whether consent is a defence to offences causing serious bodily injury.',
    decision: 'The House of Lords limited consent as a defence for serious injury outside accepted categories.',
    principle: 'Consent does not generally excuse intentional infliction of serious bodily harm.',
    statutes: ['Offences Against the Person Act 1861 ss 20, 47'],
    lawyerNote: 'Use carefully in assault cases involving consent, sport, surgery, and public policy exceptions.',
    keywords: ['consent', 'assault', 'actual bodily harm'],
  },
  {
    id: 'uk-008',
    title: 'R v G and another',
    jurisdiction: 'england-wales',
    practiceArea: 'Criminal',
    court: 'House of Lords',
    year: '2003',
    citation: '[2003] UKHL 50',
    location: 'England & Wales',
    sourceLabel: 'BAILII',
    sourceUrl: 'https://www.bailii.org/uk/cases/UKHL/2003/50.html',
    facts: 'Two children set fire to newspapers, causing extensive damage.',
    issue: 'Whether recklessness should be objective or subjective in criminal damage.',
    decision: 'The court restored a subjective recklessness approach.',
    principle: 'Recklessness requires awareness of a risk and unreasonable taking of that risk.',
    statutes: ['Criminal Damage Act 1971 s 1'],
    lawyerNote: 'Use for mens rea analysis, youth defendants, and subjective risk awareness.',
    keywords: ['recklessness', 'criminal damage', 'mens rea'],
  },
  {
    id: 'uk-009',
    title: 'Carlill v Carbolic Smoke Ball Co',
    jurisdiction: 'england-wales',
    practiceArea: 'Contract / Commercial',
    court: 'Court of Appeal',
    year: '1893',
    citation: '[1893] 1 QB 256',
    location: 'England & Wales',
    sourceLabel: 'BAILII',
    sourceUrl: 'https://www.bailii.org/ew/cases/EWCA/Civ/1892/1.html',
    facts: 'A company advertised a reward to users who caught influenza after using its product as directed.',
    issue: 'Whether an advertisement could be a unilateral offer accepted by performance.',
    decision: 'The court held the advertisement was capable of creating a binding unilateral contract.',
    principle: 'Clear promise, intention, and performance can form a unilateral contract.',
    statutes: ['Common law contract'],
    lawyerNote: 'Use for offer, acceptance, intention, and consumer advertisement disputes.',
    keywords: ['offer', 'acceptance', 'unilateral contract', 'advertisement'],
  },
  {
    id: 'uk-010',
    title: 'Cavendish Square Holding BV v Makdessi; ParkingEye Ltd v Beavis',
    jurisdiction: 'england-wales',
    practiceArea: 'Contract / Commercial',
    court: 'UK Supreme Court',
    year: '2015',
    citation: '[2015] UKSC 67',
    location: 'England & Wales',
    sourceLabel: 'UK Supreme Court',
    sourceUrl: 'https://www.supremecourt.uk/cases/uksc-2013-0280.html',
    facts: 'The appeals reconsidered penalty clauses in commercial contracts and consumer parking charges.',
    issue: 'When is a contractual sum an unenforceable penalty rather than a valid protective clause.',
    decision: 'The Supreme Court reformulated the penalty test around legitimate interest and proportionality.',
    principle: 'A clause is penal if it imposes a detriment out of all proportion to a legitimate interest.',
    statutes: ['Consumer Rights Act 2015', 'Common law penalties'],
    lawyerNote: 'Use for liquidated damages, parking charges, default clauses, and commercial risk allocation.',
    keywords: ['penalty clause', 'liquidated damages', 'commercial contract'],
  },
  {
    id: 'uk-011',
    title: 'Arnold v Britton',
    jurisdiction: 'england-wales',
    practiceArea: 'Contract / Commercial',
    court: 'UK Supreme Court',
    year: '2015',
    citation: '[2015] UKSC 36',
    location: 'Wales',
    sourceLabel: 'UK Supreme Court',
    sourceUrl: 'https://www.supremecourt.uk/cases/uksc-2013-0193.html',
    facts: 'Holiday chalet leases contained service charge wording that produced commercially harsh escalation.',
    issue: 'Whether commercial common sense could override the natural meaning of the contract.',
    decision: 'The court prioritized the language used, even if the outcome was burdensome.',
    principle: 'Contract interpretation starts with the words chosen, read in documentary and commercial context.',
    statutes: ['Common law contract interpretation'],
    lawyerNote: 'Use for drafting warnings: precise wording can defeat later commercial-common-sense arguments.',
    keywords: ['contract interpretation', 'lease', 'service charge'],
  },
  {
    id: 'uk-012',
    title: 'Wood v Capita Insurance Services Ltd',
    jurisdiction: 'england-wales',
    practiceArea: 'Contract / Commercial',
    court: 'UK Supreme Court',
    year: '2017',
    citation: '[2017] UKSC 24',
    location: 'England & Wales',
    sourceLabel: 'UK Supreme Court',
    sourceUrl: 'https://www.supremecourt.uk/cases/uksc-2015-0212.html',
    facts: 'A share purchase agreement indemnity was disputed after regulatory compensation became payable.',
    issue: 'How textualism and commercial context interact in contract interpretation.',
    decision: 'The court treated text and context as tools in a single iterative process.',
    principle: 'Interpretation balances language, context, and commercial consequences without rewriting the bargain.',
    statutes: ['Common law contract interpretation'],
    lawyerNote: 'Use when parties argue either strict wording or commercial purpose in a commercial agreement.',
    keywords: ['indemnity', 'contract interpretation', 'commercial context'],
  },
  {
    id: 'uk-013',
    title: 'Stack v Dowden',
    jurisdiction: 'england-wales',
    practiceArea: 'Land / Property',
    court: 'House of Lords',
    year: '2007',
    citation: '[2007] UKHL 17',
    location: 'England & Wales',
    sourceLabel: 'BAILII',
    sourceUrl: 'https://www.bailii.org/uk/cases/UKHL/2007/17.html',
    facts: 'An unmarried couple disputed beneficial shares in a family home held in joint names.',
    issue: 'How beneficial ownership should be inferred in domestic property disputes.',
    decision: 'The court considered whole-course dealings and presumed joint beneficial ownership absent contrary evidence.',
    principle: 'Domestic beneficial ownership depends on common intention and the parties’ overall conduct.',
    statutes: ['Trusts of Land and Appointment of Trustees Act 1996'],
    lawyerNote: 'Use in cohabitation, family property, and resulting/constructive trust arguments.',
    keywords: ['beneficial ownership', 'constructive trust', 'cohabitation'],
  },
  {
    id: 'uk-014',
    title: 'Jones v Kernott',
    jurisdiction: 'england-wales',
    practiceArea: 'Land / Property',
    court: 'UK Supreme Court',
    year: '2011',
    citation: '[2011] UKSC 53',
    location: 'England & Wales',
    sourceLabel: 'UK Supreme Court',
    sourceUrl: 'https://www.supremecourt.uk/cases/uksc-2010-0130.html',
    facts: 'Former partners disputed changed beneficial shares after separation and years of sole payment by one party.',
    issue: 'Whether courts can infer or impute changed common intention over time.',
    decision: 'The Supreme Court adjusted shares based on inferred or imputed intention and fair dealing.',
    principle: 'Common intention in home ownership can evolve after purchase.',
    statutes: ['Trusts of Land and Appointment of Trustees Act 1996'],
    lawyerNote: 'Use after Stack where long separation or payment history changes beneficial ownership analysis.',
    keywords: ['cohabitation', 'beneficial shares', 'common intention'],
  },
  {
    id: 'uk-015',
    title: 'Manchester Ship Canal Co Ltd v Vauxhall Motors Ltd',
    jurisdiction: 'england-wales',
    practiceArea: 'Land / Property',
    court: 'UK Supreme Court',
    year: '2019',
    citation: '[2019] UKSC 46',
    location: 'England',
    sourceLabel: 'UK Supreme Court',
    sourceUrl: 'https://www.supremecourt.uk/cases/uksc-2018-0091.html',
    facts: 'A landowner sought possession against a long-term licensee of canal-side discharge rights.',
    issue: 'Whether relief from forfeiture could apply to possessory or proprietary licences.',
    decision: 'The Supreme Court recognized relief from forfeiture in the circumstances.',
    principle: 'Equitable relief can protect valuable property-related rights from strict termination.',
    statutes: ['Common law property', 'Equity'],
    lawyerNote: 'Use in licence, lease-like rights, and forfeiture relief applications.',
    keywords: ['licence', 'forfeiture', 'equity', 'property rights'],
  },
  {
    id: 'uk-016',
    title: 'R (Miller) v Prime Minister',
    jurisdiction: 'england-wales',
    practiceArea: 'Constitutional / Human Rights',
    court: 'UK Supreme Court',
    year: '2019',
    citation: '[2019] UKSC 41',
    location: 'United Kingdom',
    sourceLabel: 'UK Supreme Court',
    sourceUrl: 'https://www.supremecourt.uk/cases/uksc-2019-0192.html',
    facts: 'The Prime Minister advised prorogation of Parliament during the Brexit process.',
    issue: 'Whether the prorogation advice was justiciable and lawful.',
    decision: 'The Supreme Court held the advice unlawful and the prorogation null.',
    principle: 'Executive power cannot frustrate parliamentary sovereignty and constitutional accountability.',
    statutes: ['Constitutional common law', 'Bill of Rights 1689 context'],
    lawyerNote: 'Use for justiciability, executive power limits, and constitutional principle arguments.',
    keywords: ['prorogation', 'parliamentary sovereignty', 'executive power'],
  },
  {
    id: 'uk-017',
    title: 'R (UNISON) v Lord Chancellor',
    jurisdiction: 'england-wales',
    practiceArea: 'Constitutional / Human Rights',
    court: 'UK Supreme Court',
    year: '2017',
    citation: '[2017] UKSC 51',
    location: 'United Kingdom',
    sourceLabel: 'UK Supreme Court',
    sourceUrl: 'https://www.supremecourt.uk/cases/uksc-2015-0233.html',
    facts: 'Employment tribunal fees were challenged as restricting access to justice.',
    issue: 'Whether fees that deter valid claims were lawful.',
    decision: 'The Supreme Court quashed the fees order.',
    principle: 'Access to courts is a constitutional right that cannot be impaired by disproportionate financial barriers.',
    statutes: ['Constitutional common law', 'Tribunals, Courts and Enforcement Act 2007'],
    lawyerNote: 'Use for court-fee, access-to-justice, and procedural barrier challenges.',
    keywords: ['access to justice', 'tribunal fees', 'constitutional rights'],
  },
  {
    id: 'us-001',
    title: 'Miranda v Arizona',
    jurisdiction: 'united-states',
    practiceArea: 'Criminal',
    court: 'U.S. Supreme Court',
    year: '1966',
    citation: '384 U.S. 436',
    location: 'United States',
    sourceLabel: 'Cornell LII',
    sourceUrl: 'https://www.law.cornell.edu/supremecourt/text/384/436',
    facts: 'Suspects were questioned in custody without standardized warnings about silence and counsel.',
    issue: 'What safeguards the Fifth Amendment requires before custodial interrogation.',
    decision: 'The Court required warnings protecting silence and counsel rights.',
    principle: 'Custodial interrogation requires procedural safeguards against compelled self-incrimination.',
    statutes: ['U.S. Const. amend. V', 'U.S. Const. amend. VI'],
    lawyerNote: 'Use for suppression motions, custodial interrogation, and waiver analysis.',
    keywords: ['Miranda', 'custody', 'interrogation', 'self-incrimination'],
  },
  {
    id: 'us-002',
    title: 'Terry v Ohio',
    jurisdiction: 'united-states',
    practiceArea: 'Criminal',
    court: 'U.S. Supreme Court',
    year: '1968',
    citation: '392 U.S. 1',
    location: 'Ohio, United States',
    sourceLabel: 'Cornell LII',
    sourceUrl: 'https://www.law.cornell.edu/supremecourt/text/392/1',
    facts: 'Police stopped and frisked men based on suspected casing of a store.',
    issue: 'When a brief stop and pat-down is permitted under the Fourth Amendment.',
    decision: 'The Court allowed stop-and-frisk on reasonable suspicion of crime and danger.',
    principle: 'Reasonable suspicion is less than probable cause but must be specific and articulable.',
    statutes: ['U.S. Const. amend. IV'],
    lawyerNote: 'Use for suppression motions involving street stops, frisk scope, and officer safety claims.',
    keywords: ['stop and frisk', 'reasonable suspicion', 'Fourth Amendment'],
  },
  {
    id: 'us-003',
    title: 'Gideon v Wainwright',
    jurisdiction: 'united-states',
    practiceArea: 'Criminal',
    court: 'U.S. Supreme Court',
    year: '1963',
    citation: '372 U.S. 335',
    location: 'Florida, United States',
    sourceLabel: 'Cornell LII',
    sourceUrl: 'https://www.law.cornell.edu/supremecourt/text/372/335',
    facts: 'An indigent felony defendant was denied appointed counsel in state court.',
    issue: 'Whether the Sixth Amendment right to counsel applies to state felony prosecutions.',
    decision: 'The Court required appointed counsel for indigent felony defendants.',
    principle: 'A fair criminal trial requires counsel for defendants unable to hire one.',
    statutes: ['U.S. Const. amend. VI', 'U.S. Const. amend. XIV'],
    lawyerNote: 'Use for counsel-right, ineffective assistance context, and state criminal procedure.',
    keywords: ['right to counsel', 'indigent defense', 'Sixth Amendment'],
  },
  {
    id: 'us-004',
    title: 'Mapp v Ohio',
    jurisdiction: 'united-states',
    practiceArea: 'Criminal',
    court: 'U.S. Supreme Court',
    year: '1961',
    citation: '367 U.S. 643',
    location: 'Ohio, United States',
    sourceLabel: 'Cornell LII',
    sourceUrl: 'https://www.law.cornell.edu/supremecourt/text/367/643',
    facts: 'Evidence was seized during a search challenged as unconstitutional.',
    issue: 'Whether the exclusionary rule applies to state criminal prosecutions.',
    decision: 'The Court applied the exclusionary rule to the states.',
    principle: 'Unconstitutionally obtained evidence may be excluded to enforce Fourth Amendment rights.',
    statutes: ['U.S. Const. amend. IV', 'U.S. Const. amend. XIV'],
    lawyerNote: 'Use for suppression motions after unlawful search and seizure.',
    keywords: ['exclusionary rule', 'search', 'Fourth Amendment'],
  },
  {
    id: 'us-005',
    title: 'Graham v Connor',
    jurisdiction: 'united-states',
    practiceArea: 'Criminal',
    court: 'U.S. Supreme Court',
    year: '1989',
    citation: '490 U.S. 386',
    location: 'North Carolina, United States',
    sourceLabel: 'Cornell LII',
    sourceUrl: 'https://www.law.cornell.edu/supremecourt/text/490/386',
    facts: 'A police stop led to an excessive force claim by a person experiencing a medical issue.',
    issue: 'What constitutional standard governs police excessive force claims during seizures.',
    decision: 'The Court applied Fourth Amendment objective reasonableness.',
    principle: 'Police force is judged from the perspective of a reasonable officer at the scene.',
    statutes: ['U.S. Const. amend. IV', '42 U.S.C. § 1983'],
    lawyerNote: 'Use for civil rights pleadings, police liability, and force reasonableness analysis.',
    keywords: ['excessive force', 'police', 'section 1983'],
  },
  {
    id: 'us-006',
    title: 'Brown v Board of Education',
    jurisdiction: 'united-states',
    practiceArea: 'Constitutional / Human Rights',
    court: 'U.S. Supreme Court',
    year: '1954',
    citation: '347 U.S. 483',
    location: 'United States',
    sourceLabel: 'Cornell LII',
    sourceUrl: 'https://www.law.cornell.edu/supremecourt/text/347/483',
    facts: 'Public school segregation was challenged under the Equal Protection Clause.',
    issue: 'Whether racially segregated public schools are constitutional.',
    decision: 'The Court held segregated public schools inherently unequal.',
    principle: 'State-imposed racial segregation violates equal protection.',
    statutes: ['U.S. Const. amend. XIV'],
    lawyerNote: 'Use as a foundational equal-protection authority.',
    keywords: ['equal protection', 'segregation', 'civil rights'],
  },
  {
    id: 'us-007',
    title: 'Marbury v Madison',
    jurisdiction: 'united-states',
    practiceArea: 'Constitutional / Human Rights',
    court: 'U.S. Supreme Court',
    year: '1803',
    citation: '5 U.S. 137',
    location: 'Washington, D.C., United States',
    sourceLabel: 'Cornell LII',
    sourceUrl: 'https://www.law.cornell.edu/supremecourt/text/5/137',
    facts: 'A commission dispute led to review of the Court’s power and congressional jurisdictional provisions.',
    issue: 'Whether courts can declare legislation unconstitutional.',
    decision: 'The Court articulated judicial review.',
    principle: 'It is the province of the judiciary to say what the law is.',
    statutes: ['U.S. Const. art. III'],
    lawyerNote: 'Use for constitutional supremacy and judicial review foundations.',
    keywords: ['judicial review', 'constitutional law', 'separation of powers'],
  },
  {
    id: 'us-008',
    title: 'Obergefell v Hodges',
    jurisdiction: 'united-states',
    practiceArea: 'Constitutional / Human Rights',
    court: 'U.S. Supreme Court',
    year: '2015',
    citation: '576 U.S. 644',
    location: 'United States',
    sourceLabel: 'Cornell LII',
    sourceUrl: 'https://www.law.cornell.edu/supremecourt/text/576/644',
    facts: 'Same-sex couples challenged state marriage restrictions.',
    issue: 'Whether the Fourteenth Amendment requires recognition and licensing of same-sex marriages.',
    decision: 'The Court recognized a constitutional right to marry for same-sex couples.',
    principle: 'Due process and equal protection protect fundamental marriage rights.',
    statutes: ['U.S. Const. amend. XIV'],
    lawyerNote: 'Use for substantive due process, equality, dignity, and family-law rights analysis.',
    keywords: ['marriage equality', 'due process', 'equal protection'],
  },
  {
    id: 'us-009',
    title: 'New York Times Co v Sullivan',
    jurisdiction: 'united-states',
    practiceArea: 'Constitutional / Human Rights',
    court: 'U.S. Supreme Court',
    year: '1964',
    citation: '376 U.S. 254',
    location: 'Alabama, United States',
    sourceLabel: 'Cornell LII',
    sourceUrl: 'https://www.law.cornell.edu/supremecourt/text/376/254',
    facts: 'A public official sued over alleged defamatory statements in a civil-rights advertisement.',
    issue: 'What First Amendment standard applies to public-official defamation claims.',
    decision: 'The Court required actual malice for public official defamation liability.',
    principle: 'Public debate receives strong constitutional protection even when factual errors occur.',
    statutes: ['U.S. Const. amend. I'],
    lawyerNote: 'Use for media defence, public figure/public official analysis, and defamation risk review.',
    keywords: ['defamation', 'actual malice', 'First Amendment'],
  },
  {
    id: 'us-010',
    title: 'Palsgraf v Long Island Railroad Co',
    jurisdiction: 'united-states',
    practiceArea: 'Road Accident / Personal Injury',
    court: 'New York Court of Appeals',
    year: '1928',
    citation: '248 N.Y. 339',
    location: 'New York, United States',
    sourceLabel: 'New York Courts Historical Society',
    sourceUrl: 'https://history.nycourts.gov/case/palsgraf-v-long-island-railroad-co/',
    facts: 'Railroad employees helped a passenger board, causing a package of fireworks to fall and injure a distant plaintiff.',
    issue: 'Whether duty and proximate cause extend to unforeseeable plaintiffs.',
    decision: 'The court denied liability because the plaintiff was outside the foreseeable zone of risk.',
    principle: 'Negligence duty is limited by foreseeability of harm to the plaintiff.',
    statutes: ['Common law negligence'],
    lawyerNote: 'Use for causation, foreseeability, and duty limits in personal injury cases.',
    keywords: ['proximate cause', 'foreseeability', 'negligence'],
  },
  {
    id: 'us-011',
    title: 'Summers v Tice',
    jurisdiction: 'united-states',
    practiceArea: 'Road Accident / Personal Injury',
    court: 'Supreme Court of California',
    year: '1948',
    citation: '33 Cal. 2d 80',
    location: 'California, United States',
    sourceLabel: 'Justia',
    sourceUrl: 'https://law.justia.com/cases/california/supreme-court/2d/33/80.html',
    facts: 'Two hunters negligently fired in the plaintiff’s direction, but only one shot caused the injury.',
    issue: 'How causation is handled when multiple negligent defendants create evidentiary uncertainty.',
    decision: 'The burden shifted to defendants to absolve themselves.',
    principle: 'Alternative liability can shift burden where multiple negligent actors create uncertainty.',
    statutes: ['Common law negligence'],
    lawyerNote: 'Use where multiple tortfeasors cause uncertainty in accident or product injury cases.',
    keywords: ['causation', 'multiple defendants', 'burden shifting'],
  },
  {
    id: 'us-012',
    title: 'MacPherson v Buick Motor Co',
    jurisdiction: 'united-states',
    practiceArea: 'Road Accident / Personal Injury',
    court: 'New York Court of Appeals',
    year: '1916',
    citation: '217 N.Y. 382',
    location: 'New York, United States',
    sourceLabel: 'New York Courts Historical Society',
    sourceUrl: 'https://history.nycourts.gov/case/macpherson-v-buick-motor-co/',
    facts: 'A defective automobile wheel injured a purchaser who lacked direct contract with the manufacturer.',
    issue: 'Whether a manufacturer owes a duty beyond immediate contractual privity.',
    decision: 'The court recognized manufacturer duty for products likely to cause danger if negligently made.',
    principle: 'Privity is not required where negligent manufacture of dangerous products foreseeably injures users.',
    statutes: ['Common law negligence', 'Product liability principles'],
    lawyerNote: 'Use for product defect and manufacturer-duty arguments in vehicle or machinery injury cases.',
    keywords: ['product liability', 'manufacturer duty', 'vehicle defect'],
  },
  {
    id: 'us-013',
    title: 'Hamer v Sidway',
    jurisdiction: 'united-states',
    practiceArea: 'Contract / Commercial',
    court: 'New York Court of Appeals',
    year: '1891',
    citation: '124 N.Y. 538',
    location: 'New York, United States',
    sourceLabel: 'New York Courts Historical Society',
    sourceUrl: 'https://history.nycourts.gov/case/hamer-v-sidway/',
    facts: 'An uncle promised money if his nephew refrained from drinking, smoking, swearing, and gambling until age 21.',
    issue: 'Whether forbearance from legal rights is valid consideration.',
    decision: 'The promise was enforceable because the nephew gave legal detriment.',
    principle: 'Consideration may consist of giving up a legal right, even if the promisor benefits only indirectly.',
    statutes: ['Common law contract'],
    lawyerNote: 'Use for consideration analysis in settlement, restraint, and promise-enforcement disputes.',
    keywords: ['consideration', 'forbearance', 'contract'],
  },
  {
    id: 'us-014',
    title: 'Lucy v Zehmer',
    jurisdiction: 'united-states',
    practiceArea: 'Contract / Commercial',
    court: 'Supreme Court of Virginia',
    year: '1954',
    citation: '196 Va. 493',
    location: 'Virginia, United States',
    sourceLabel: 'CourtListener',
    sourceUrl: 'https://www.courtlistener.com/opinion/1362244/lucy-v-zehmer/',
    facts: 'A written agreement to sell a farm was later claimed to have been made jokingly over drinks.',
    issue: 'Whether outward manifestations showed contractual intent despite a claimed secret intention not to contract.',
    decision: 'The court enforced the agreement.',
    principle: 'Contract formation is judged objectively by outward words and acts.',
    statutes: ['Common law contract'],
    lawyerNote: 'Use for objective intention, informal agreements, and signed memorandum disputes.',
    keywords: ['objective theory', 'contract formation', 'specific performance'],
  },
  {
    id: 'us-015',
    title: 'Hawkins v McGee',
    jurisdiction: 'united-states',
    practiceArea: 'Contract / Commercial',
    court: 'Supreme Court of New Hampshire',
    year: '1929',
    citation: '84 N.H. 114',
    location: 'New Hampshire, United States',
    sourceLabel: 'CourtListener',
    sourceUrl: 'https://www.courtlistener.com/opinion/3553065/hawkins-v-mcgee/',
    facts: 'A doctor allegedly promised a perfect or good hand after surgery, but the outcome was poor.',
    issue: 'How expectation damages are measured for breach of a promised result.',
    decision: 'The court applied expectation damages rather than pain-and-suffering tort damages for the contract claim.',
    principle: 'Contract damages aim to place the claimant in the position promised by performance.',
    statutes: ['Common law contract damages'],
    lawyerNote: 'Use for expectation damages, professional promises, and contract/tort boundary analysis.',
    keywords: ['damages', 'expectation interest', 'breach of contract'],
  },
  {
    id: 'us-016',
    title: 'Pierson v Post',
    jurisdiction: 'united-states',
    practiceArea: 'Land / Property',
    court: 'New York Supreme Court',
    year: '1805',
    citation: '3 Cai. R. 175',
    location: 'New York, United States',
    sourceLabel: 'New York Courts Historical Society',
    sourceUrl: 'https://history.nycourts.gov/case/pierson-v-post/',
    facts: 'A hunter pursued a fox, but another person killed and took it.',
    issue: 'When property rights arise in wild animals.',
    decision: 'The court required capture or mortal wounding, not mere pursuit.',
    principle: 'Property rights in unowned resources generally require possession or control.',
    statutes: ['Common law property'],
    lawyerNote: 'Use as a teaching case for possession, first-in-time, and property acquisition theory.',
    keywords: ['possession', 'property', 'capture'],
  },
  {
    id: 'us-017',
    title: 'Kelo v City of New London',
    jurisdiction: 'united-states',
    practiceArea: 'Land / Property',
    court: 'U.S. Supreme Court',
    year: '2005',
    citation: '545 U.S. 469',
    location: 'Connecticut, United States',
    sourceLabel: 'Cornell LII',
    sourceUrl: 'https://www.law.cornell.edu/supremecourt/text/545/469',
    facts: 'Homeowners challenged eminent-domain taking for an economic development plan.',
    issue: 'Whether economic development can qualify as public use under the Fifth Amendment.',
    decision: 'The Court upheld the taking under a broad public-use interpretation.',
    principle: 'Public use can include public purpose, subject to state-law limits and political safeguards.',
    statutes: ['U.S. Const. amend. V'],
    lawyerNote: 'Use for takings, eminent domain, compensation, and public-purpose challenges.',
    keywords: ['eminent domain', 'takings', 'public use', 'property'],
  },
];

export const statutes = [
  { id: 'bd-s-001', jurisdiction: 'bangladesh', area: 'Constitutional / Human Rights', title: 'Constitution of Bangladesh art 27', section: 'Equality before law', sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-367/section-24549.html', note: 'Use in equal protection and arbitrary state action challenges.' },
  { id: 'bd-s-002', jurisdiction: 'bangladesh', area: 'Constitutional / Human Rights', title: 'Constitution of Bangladesh art 31', section: 'Right to protection of law', sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-367/section-24553.html', note: 'Core due process-style provision for writs and rights litigation.' },
  { id: 'bd-s-003', jurisdiction: 'bangladesh', area: 'Constitutional / Human Rights', title: 'Constitution of Bangladesh art 32', section: 'Protection of life and personal liberty', sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-367/section-24554.html', note: 'Use in detention, public safety, health, environment, and compensation claims.' },
  { id: 'bd-s-004', jurisdiction: 'bangladesh', area: 'Criminal', title: 'Constitution of Bangladesh art 35', section: 'Protection in respect of trial and punishment', sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-367/section-24557.html', note: 'Use for fair trial, double jeopardy, self-incrimination, and punishment arguments.' },
  { id: 'bd-s-005', jurisdiction: 'bangladesh', area: 'Land / Property', title: 'Constitution of Bangladesh art 42', section: 'Right to property', sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-367/section-24564.html', note: 'Use in acquisition, eviction, compensation, and property-rights writs.' },
  { id: 'bd-s-006', jurisdiction: 'bangladesh', area: 'Constitutional / Human Rights', title: 'Constitution of Bangladesh art 102', section: 'High Court Division writ jurisdiction', sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-367/section-24638.html', note: 'The primary constitutional route for public law remedies.' },
  { id: 'bd-s-007', jurisdiction: 'bangladesh', area: 'Criminal', title: 'Penal Code 1860 s 302', section: 'Punishment for murder', sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-11/section-3233.html', note: 'Charging and sentencing anchor for murder.' },
  { id: 'bd-s-008', jurisdiction: 'bangladesh', area: 'Road Accident / Personal Injury', title: 'Penal Code 1860 s 304A', section: 'Causing death by negligence', sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-11/section-3236.html', note: 'Often relevant in fatal road and workplace accident cases.' },
  { id: 'bd-s-008a', jurisdiction: 'bangladesh', area: 'Criminal', title: 'Penal Code 1860 s 420', section: 'Cheating and dishonestly inducing delivery of property', sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-11/act-chapter-print-20.html', note: 'Use for cheating allegations involving deception, dishonest inducement, and delivery or alteration of property or valuable security.' },
  { id: 'bd-s-009', jurisdiction: 'bangladesh', area: 'Criminal', title: 'Code of Criminal Procedure 1898 s 54', section: 'Arrest without warrant', sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-75/section-21785.html', note: 'Read with BLAST v Bangladesh safeguards.' },
  { id: 'bd-s-010', jurisdiction: 'bangladesh', area: 'Criminal', title: 'Code of Criminal Procedure 1898 s 167', section: 'Remand and detention during investigation', sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-75/section-21918.html', note: 'Key provision for remand opposition and custody safeguards.' },
  { id: 'bd-s-011', jurisdiction: 'bangladesh', area: 'Road Accident / Personal Injury', title: 'Road Transport Act 2018 ss 53-54', section: 'Financial assistance fund and trustee board', sourceUrl: 'https://www.tbsnews.net/bangladesh/hc-issues-rule-over-compensation-road-accident-victims-298654', note: 'Use in compensation fund arguments for road accident victims.' },
  { id: 'bd-s-012', jurisdiction: 'bangladesh', area: 'Road Accident / Personal Injury', title: 'Road Transport Act 2018 s 105', section: 'Crimes concerning accidents', sourceUrl: 'https://link.springer.com/article/10.1057/s41300-022-00146-0', note: 'Accident offences may be tied back to Penal Code provisions.' },
  { id: 'bd-s-013', jurisdiction: 'bangladesh', area: 'Road Accident / Personal Injury', title: 'Fatal Accidents Act 1855', section: 'Family compensation after death by wrongful act', sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-10.html', note: 'Use for dependency and fatal accident compensation claims.' },
  { id: 'bd-s-014', jurisdiction: 'bangladesh', area: 'Land / Property', title: 'Environment Conservation Act 1995', section: 'Environmental clearance and protection framework', sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-791.html', note: 'Useful in land development, pollution, wetland, and public safety cases.' },
  { id: 'bd-s-015', jurisdiction: 'bangladesh', area: 'Land / Property', title: 'Natural Water Reservoir Conservation Act 2000', section: 'Protection of natural water reservoirs', sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-849.html', note: 'Use in wetland, flood-flow zone, and urban development disputes.' },
  { id: 'uk-s-001', jurisdiction: 'england-wales', area: 'Road Accident / Personal Injury', title: 'Road Traffic Act 1988 s 1', section: 'Causing death by dangerous driving', sourceUrl: 'https://www.legislation.gov.uk/ukpga/1988/52/section/1', note: 'Primary criminal road-death provision.' },
  { id: 'uk-s-002', jurisdiction: 'england-wales', area: 'Road Accident / Personal Injury', title: 'Road Traffic Act 1988 s 2', section: 'Dangerous driving', sourceUrl: 'https://www.legislation.gov.uk/ukpga/1988/52/section/2', note: 'Use for serious driving conduct falling far below standard.' },
  { id: 'uk-s-003', jurisdiction: 'england-wales', area: 'Road Accident / Personal Injury', title: 'Road Traffic Act 1988 s 3', section: 'Careless and inconsiderate driving', sourceUrl: 'https://www.legislation.gov.uk/ukpga/1988/52/section/3', note: 'Use for careless driving and related accident liability.' },
  { id: 'uk-s-004', jurisdiction: 'england-wales', area: 'Criminal', title: 'Police and Criminal Evidence Act 1984 s 24', section: 'Arrest without warrant', sourceUrl: 'https://www.legislation.gov.uk/ukpga/1984/60/section/24', note: 'Assess necessity and grounds for arrest.' },
  { id: 'uk-s-005', jurisdiction: 'england-wales', area: 'Criminal', title: 'Police and Criminal Evidence Act 1984 s 78', section: 'Exclusion of unfair evidence', sourceUrl: 'https://www.legislation.gov.uk/ukpga/1984/60/section/78', note: 'Use in evidence exclusion applications.' },
  { id: 'uk-s-006', jurisdiction: 'england-wales', area: 'Criminal', title: 'Offences Against the Person Act 1861 s 18', section: 'Wounding with intent', sourceUrl: 'https://www.legislation.gov.uk/ukpga/Vict/24-25/100/section/18', note: 'Serious violence offence requiring specific intent.' },
  { id: 'uk-s-007', jurisdiction: 'england-wales', area: 'Criminal', title: 'Theft Act 1968 s 1', section: 'Basic definition of theft', sourceUrl: 'https://www.legislation.gov.uk/ukpga/1968/60/section/1', note: 'Use for dishonesty, appropriation, property, and intention analysis.' },
  { id: 'uk-s-008', jurisdiction: 'england-wales', area: 'Contract / Commercial', title: 'Consumer Rights Act 2015 s 62', section: 'Requirement for fair consumer contract terms', sourceUrl: 'https://www.legislation.gov.uk/ukpga/2015/15/section/62', note: 'Use in unfair term review and consumer disputes.' },
  { id: 'uk-s-009', jurisdiction: 'england-wales', area: 'Land / Property', title: 'Law of Property Act 1925 s 52', section: 'Conveyances by deed', sourceUrl: 'https://www.legislation.gov.uk/ukpga/Geo5/15-16/20/section/52', note: 'Formalities for legal estates and conveyances.' },
  { id: 'uk-s-010', jurisdiction: 'england-wales', area: 'Land / Property', title: 'Law of Property Act 1925 s 53', section: 'Writing requirements for certain interests', sourceUrl: 'https://www.legislation.gov.uk/ukpga/Geo5/15-16/20/section/53', note: 'Use for trusts and land-interest formalities.' },
  { id: 'uk-s-011', jurisdiction: 'england-wales', area: 'Land / Property', title: 'Land Registration Act 2002 s 58', section: 'Conclusiveness of register', sourceUrl: 'https://www.legislation.gov.uk/ukpga/2002/9/section/58', note: 'Important for registered title disputes.' },
  { id: 'uk-s-012', jurisdiction: 'england-wales', area: 'Constitutional / Human Rights', title: 'Human Rights Act 1998 s 6', section: 'Public authority acts', sourceUrl: 'https://www.legislation.gov.uk/ukpga/1998/42/section/6', note: 'Public authorities must act compatibly with Convention rights.' },
  { id: 'uk-s-013', jurisdiction: 'england-wales', area: 'Constitutional / Human Rights', title: 'Equality Act 2010 s 13', section: 'Direct discrimination', sourceUrl: 'https://www.legislation.gov.uk/ukpga/2010/15/section/13', note: 'Core equality provision for discrimination analysis.' },
  { id: 'uk-s-014', jurisdiction: 'england-wales', area: 'Road Accident / Personal Injury', title: 'Occupiers Liability Act 1957 s 2', section: 'Common duty of care to visitors', sourceUrl: 'https://www.legislation.gov.uk/ukpga/Eliz2/5-6/31/section/2', note: 'Use in premises liability and visitor injury claims.' },
  { id: 'uk-s-015', jurisdiction: 'england-wales', area: 'Contract / Commercial', title: 'Sale of Goods Act 1979 s 14', section: 'Quality and fitness terms', sourceUrl: 'https://www.legislation.gov.uk/ukpga/1979/54/section/14', note: 'Useful in business sale-of-goods disputes.' },
  { id: 'us-s-001', jurisdiction: 'united-states', area: 'Criminal', title: 'U.S. Constitution Amendment IV', section: 'Search and seizure', sourceUrl: 'https://www.law.cornell.edu/constitution/fourth_amendment', note: 'Foundation for suppression and police-search litigation.' },
  { id: 'us-s-002', jurisdiction: 'united-states', area: 'Criminal', title: 'U.S. Constitution Amendment V', section: 'Self-incrimination and due process', sourceUrl: 'https://www.law.cornell.edu/constitution/fifth_amendment', note: 'Use for Miranda, takings, indictment, and due process analysis.' },
  { id: 'us-s-003', jurisdiction: 'united-states', area: 'Criminal', title: 'U.S. Constitution Amendment VI', section: 'Criminal trial rights', sourceUrl: 'https://www.law.cornell.edu/constitution/sixth_amendment', note: 'Covers counsel, confrontation, jury, and speedy trial rights.' },
  { id: 'us-s-004', jurisdiction: 'united-states', area: 'Constitutional / Human Rights', title: 'U.S. Constitution Amendment XIV', section: 'Due process and equal protection', sourceUrl: 'https://www.law.cornell.edu/constitution/amendmentxiv', note: 'Core civil-rights and incorporation provision.' },
  { id: 'us-s-005', jurisdiction: 'united-states', area: 'Constitutional / Human Rights', title: '42 U.S.C. § 1983', section: 'Civil action for deprivation of rights', sourceUrl: 'https://www.law.cornell.edu/uscode/text/42/1983', note: 'Primary federal civil-rights damages vehicle against state actors.' },
  { id: 'us-s-006', jurisdiction: 'united-states', area: 'Contract / Commercial', title: 'UCC § 2-201', section: 'Statute of frauds for sale of goods', sourceUrl: 'https://www.law.cornell.edu/ucc/2/2-201', note: 'Writing requirement for goods contracts over threshold value.' },
  { id: 'us-s-007', jurisdiction: 'united-states', area: 'Contract / Commercial', title: 'UCC § 2-207', section: 'Additional terms in acceptance or confirmation', sourceUrl: 'https://www.law.cornell.edu/ucc/2/2-207', note: 'Battle-of-the-forms provision for merchants and sales contracts.' },
  { id: 'us-s-008', jurisdiction: 'united-states', area: 'Contract / Commercial', title: 'UCC § 2-314', section: 'Implied warranty of merchantability', sourceUrl: 'https://www.law.cornell.edu/ucc/2/2-314', note: 'Use in goods quality and product-dispute claims.' },
  { id: 'us-s-009', jurisdiction: 'united-states', area: 'Land / Property', title: 'U.S. Constitution Amendment V', section: 'Takings Clause', sourceUrl: 'https://www.law.cornell.edu/constitution/fifth_amendment', note: 'Private property cannot be taken for public use without just compensation.' },
  { id: 'us-s-010', jurisdiction: 'united-states', area: 'Road Accident / Personal Injury', title: 'Federal Rule of Evidence 401', section: 'Test for relevant evidence', sourceUrl: 'https://www.law.cornell.edu/rules/fre/rule_401', note: 'Use for evidence relevance in injury and liability disputes.' },
  { id: 'us-s-011', jurisdiction: 'united-states', area: 'Road Accident / Personal Injury', title: 'Federal Rule of Evidence 403', section: 'Excluding relevant evidence for prejudice or confusion', sourceUrl: 'https://www.law.cornell.edu/rules/fre/rule_403', note: 'Use in motions in limine and trial evidence strategy.' },
  { id: 'us-s-012', jurisdiction: 'united-states', area: 'Constitutional / Human Rights', title: '28 U.S.C. § 1331', section: 'Federal question jurisdiction', sourceUrl: 'https://www.law.cornell.edu/uscode/text/28/1331', note: 'Federal jurisdiction basis for claims arising under federal law.' },
  { id: 'us-s-013', jurisdiction: 'united-states', area: 'Contract / Commercial', title: 'Federal Rule of Civil Procedure 12(b)(6)', section: 'Failure to state a claim', sourceUrl: 'https://www.law.cornell.edu/rules/frcp/rule_12', note: 'Use for pleading-stage dismissal strategy.' },
  { id: 'us-s-014', jurisdiction: 'united-states', area: 'Contract / Commercial', title: 'Federal Rule of Civil Procedure 56', section: 'Summary judgment', sourceUrl: 'https://www.law.cornell.edu/rules/frcp/rule_56', note: 'Use when no genuine dispute of material fact remains.' },
  { id: 'us-s-015', jurisdiction: 'united-states', area: 'Criminal', title: 'Model Penal Code § 2.02', section: 'General requirements of culpability', sourceUrl: 'https://www.law.cornell.edu/wex/model_penal_code', note: 'Persuasive framework for purpose, knowledge, recklessness, and negligence.' },
  { id: 'us-s-016', jurisdiction: 'united-states', area: 'Land / Property', title: '42 U.S.C. § 3604', section: 'Fair Housing Act discrimination in housing', sourceUrl: 'https://www.law.cornell.edu/uscode/text/42/3604', note: 'Use in housing discrimination and property access disputes.' },
];

export const draftTemplates = [
  {
    id: 'legal-notice',
    name: 'Legal Notice / Demand Letter',
    heading: 'LEGAL NOTICE',
    purpose: 'Demand compliance, payment, compensation, or corrective action before litigation.',
  },
  {
    id: 'case-brief',
    name: 'Case Brief',
    heading: 'CASE BRIEF',
    purpose: 'Summarize facts, issues, holding, ratio, authorities, and next action.',
  },
  {
    id: 'bail-petition',
    name: 'Bail Petition Skeleton',
    heading: 'BAIL PETITION SKELETON',
    purpose: 'Create a supervised lawyer draft for bail grounds and supporting facts.',
  },
  {
    id: 'hearing-note',
    name: 'Hearing Note',
    heading: 'HEARING NOTE',
    purpose: 'Prepare concise submissions, issues, authorities, and orders sought.',
  },
  {
    id: 'client-advice',
    name: 'Client Advice Memo',
    heading: 'CLIENT ADVICE MEMO',
    purpose: 'Give a structured client-facing legal position subject to lawyer review.',
  },
  {
    id: 'settlement-proposal',
    name: 'Settlement Proposal',
    heading: 'WITHOUT PREJUDICE SETTLEMENT PROPOSAL',
    purpose: 'Frame liability, evidence, commercial risk, and proposed resolution.',
  },
];
